name: CI

on:
  pull_request:
    branches:
      - [ develop ]
      - [ main ]

  workflow_dispatch:

env:
  POSTGRES_VERSION: 13.1
  POSTGRES_DB: trading_site_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Pa$$word47
  JAVA_VERSION: 1.11

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health_interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend
