name: Java CI with Maven

on:
  - push
  - pull_request

env:
  POSTGRESQL_VERSION: 13.1
  POSTGRESQL_DB: trading_site_db
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: Pa$$word47
  JAVA_VERSION: 1.15
  NODE_VERSION: 14.16.1

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION}}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
        - working-directory: ./frontend
        - run: npm ci
        - run: npm run test:prod
        - run: npm run lint
          
